"""add policy and regulation tables

Revision ID: 413520408e49
Revises: a77c777ef31a
Create Date: 2026-03-03 16:15:20.008362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413520408e49'
down_revision = 'a77c777ef31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_regulation',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assessment_policy_regulation',
    sa.Column('demographics_id', sa.Integer(), nullable=False),
    sa.Column('policy_regulation_id', sa.Integer(), nullable=False),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('section_details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demographics_id'], ['demographics.id'], ),
    sa.ForeignKeyConstraint(['policy_regulation_id'], ['policy_regulation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demographics_id', 'policy_regulation_id', name='uq_assessment_policy')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_policy_regulation')
    op.drop_table('policy_regulation')
    # ### end Alembic commands ###
