"""add initial risk and response model

Revision ID: a061b9364f0a
Revises: aa10d6cd5fef
Create Date: 2026-03-04 09:50:09.281749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a061b9364f0a'
down_revision = 'aa10d6cd5fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_response',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('initial_risk',
    sa.Column('demographics_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.String(length=50), nullable=False),
    sa.Column('impact', sa.String(length=50), nullable=False),
    sa.Column('risk_statement', sa.Text(), nullable=False),
    sa.Column('risk_response_id', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demographics_id'], ['demographics.id'], ),
    sa.ForeignKeyConstraint(['risk_response_id'], ['risk_response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('initial_risk')
    op.drop_table('risk_response')
    # ### end Alembic commands ###
