"""add: base, choice, and demographics tables

Revision ID: a77c777ef31a
Revises: 
Create Date: 2026-03-03 16:07:14.458985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77c777ef31a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_crown_jewels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('global_process',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('process_level',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('demographics',
    sa.Column('date_of_assessment', sa.DateTime(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('design_or_execution', sa.String(length=50), nullable=False),
    sa.Column('global_process_id', sa.Integer(), nullable=False),
    sa.Column('process_level_id', sa.Integer(), nullable=False),
    sa.Column('asset_crown_jewels_id', sa.Integer(), nullable=False),
    sa.Column('geography_market_contract', sa.String(length=255), nullable=True),
    sa.Column('other_details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_crown_jewels_id'], ['asset_crown_jewels.id'], ),
    sa.ForeignKeyConstraint(['global_process_id'], ['global_process.id'], ),
    sa.ForeignKeyConstraint(['process_level_id'], ['process_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demographics')
    op.drop_table('process_level')
    op.drop_table('global_process')
    op.drop_table('asset_crown_jewels')
    # ### end Alembic commands ###
