"""add: impact models

Revision ID: aa10d6cd5fef
Revises: e325950863f5
Create Date: 2026-03-04 09:41:31.660484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa10d6cd5fef'
down_revision = 'e325950863f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_category',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assessment_impact',
    sa.Column('demographics_id', sa.Integer(), nullable=False),
    sa.Column('impact_category_id', sa.Integer(), nullable=False),
    sa.Column('adverse_effect', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demographics_id'], ['demographics.id'], ),
    sa.ForeignKeyConstraint(['impact_category_id'], ['impact_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demographics_id', 'impact_category_id', name='uq_assessment_impact')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_impact')
    op.drop_table('impact_category')
    # ### end Alembic commands ###
