"""add threat tables

Revision ID: ba5cb5481efb
Revises: cfe2d1c415e3
Create Date: 2026-03-03 16:48:13.643859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5cb5481efb'
down_revision = 'cfe2d1c415e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_source',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assessment_threat',
    sa.Column('demographics_id', sa.Integer(), nullable=False),
    sa.Column('threat_source_id', sa.Integer(), nullable=False),
    sa.Column('main_threat_event', sa.Text(), nullable=False),
    sa.Column('mitigation_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demographics_id'], ['demographics.id'], ),
    sa.ForeignKeyConstraint(['threat_source_id'], ['threat_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_threat')
    op.drop_table('threat_source')
    # ### end Alembic commands ###
