"""add assessment threat probability table

Revision ID: e325950863f5
Revises: ba5cb5481efb
Create Date: 2026-03-03 17:07:47.255657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e325950863f5'
down_revision = 'ba5cb5481efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_threat_probability',
    sa.Column('assessment_threat_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.String(length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('impact_probability', sa.String(length=50), nullable=False),
    sa.Column('impact_justification', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_threat_id'], ['assessment_threat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_threat_id')
    )
    with op.batch_alter_table('threat_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threat_category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('initiation_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('actor', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('action', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threat_source', schema=None) as batch_op:
        batch_op.drop_column('action')
        batch_op.drop_column('actor')
        batch_op.drop_column('initiation_type')
        batch_op.drop_column('threat_category')

    op.drop_table('assessment_threat_probability')
    # ### end Alembic commands ###
